global using Conesoft.Tools;
global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Linq;
global using System.Runtime.InteropServices;
global using System.Text.Json;
global using System.Threading.Tasks;
global using Env = System.Environment;
global using IO = System.IO;