on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - uses: conesoft/publish-nuget@main
        with:
          NUGET_KEY: ${{secrets.NUGET_KEY}}
